# Generated by Django 5.0 on 2023-12-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_funcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
